name: Unbreakable International
favicon: null
layout_spectrum: 0.2598257246427238
typography_spectrum: 0.5893848605919629
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.42569115455262363
  lightness: 0.34738522325642407
  saturation: 0.40721672773361206
  rhythmicContrast: 0.11537869973108172
purpose: []
